### ISSUE TITLE
add BLEBBED and BLEBBING to dictionary

### ISSUE THREAD

**Issue by DrJameson** [freebee-game/enable#1]
The words blebbed and blebbing are not included in the dictionary. When a cell goes through apoptosis it breaks up the cytoplasmic structural proteins which causes the cellular membrane to swell and break off into small pieces. This is called membrane BLEBBING. A cell that has undergone this step of apoptosis has BLEBBED. 
Bleb is included in the dictionary so these derivations should be as well.

**Comment by ibara** [comment]
Hi --

Sure. We can do that. Give me a day or two to get to this.

Thanks.

**Comment by ibara** [comment]
Sorry it took so long. These words have been added. Thanks.
