### ISSUE TITLE
Add Seal

### ISSUE THREAD

**Issue by Scubaddin** [freebee-game/enable#108]
noun
1.
a device or substance that is used to join two things together so as to prevent them from coming apart or to prevent anything from passing between them.
"blue smoke from the exhaust suggests worn valve seals"
verb
1.
fasten or close securely.
"he folded it, sealed the envelope, and walked to the mailbox"

**Comment by ibara** [comment]
This word is already in the dictionary. Line 132663.
Could you please provide a screenshot of a game where this word was not accepted?
