### ISSUE TITLE
May 25 - consider adding bento and bonobo please

### ISSUE THREAD

**Issue by Twinkycactus** [freebee-game/enable#1186]
Bento: a Japanese-style packed lunch (= a light meal that you take to eat at work or school), usually in a special box with separate parts or containers inside it (Cambridge)

bonobo - : a rare anthropoid ape (Pan paniscus) that has a more slender build and longer limbs than the related common chimpanzee (P. troglodytes) and that inhabits a small geographic region in equatorial Africa south of the Congo River
 called also pygmy chimpanzee (merriam Webster)

**Comment by DrJameson** [comment]
Good suggestions! I also suggested bonobo and bonobos.

**Comment by ibara** [comment]
Bonobo at least will start appearing starting July 1. Still reviewing other words for inclusion starting in that time frame as well.

**Comment by DrJameson** [comment]
great!
