### ISSUE TITLE
Please add Bonobo and Bonobos

### ISSUE THREAD

**Issue by freebee27** [freebee-game/enable#1304]

**Comment by mungbean** [comment]
this has to be one of the most requested additions, but it's still not in there...

**Comment by mungbean** [comment]
Are we all doing this wrong?  Maybe some instructions on how to get stuff added would help.

**Comment by ibara** [comment]
No, you're not doing it wrong.

Just that there is something additional that can be done (a PR).

I will try to get around to adding these words to the wordlist soon.

**Comment by mungbean** [comment]
Thanks Brian, I'm sure everyone else really appreciates what you're doing with keeping this alive!  PR is pull request is it?  I expect most users of freebee.fun don't have much experience with github.
