### ISSUE TITLE
i hate your font

### ISSUE THREAD

**Issue by sweetsue62** [freebee-game/enable#132]
Come on guys, there's a zillion fonts out there, and you picked this one?  Why???

**Comment by ibara** [comment]
Noto Sans is freely licensed (https://opensource.org/licenses/OFL-1.1) and is a well-known and generally well-liked font.
I don't see much problem with it. No one else before you seems to have a problem with it either.

I'm not very likely to change from Noto Sans to something else. But thanks for the report.
