### ISSUE TITLE
Please add kegel. Every woman who has had kids knows what that is 

### ISSUE THREAD

**Issue by Mamagelicious** [freebee-game/enable#1322]

**Comment by nauticalnun** [comment]
I literally just created an account specifically to ask for this!

**Comment by nauticalnun** [comment]
> I meant to say kegel

I literally just created an account to ask for this!

**Comment by ibara** [comment]
Some men too (though, admittedly, not this man).

Unfortunately though, Kegel is a proper noun (after Arnold Kegel, its namesake). It's not legal in any Scrabble dictionary or Words with Friends. The closest legal word is the anagram "gleek."
