### ISSUE TITLE
Addto puzzle the word

### ISSUE THREAD

**Issue by margowolf52** [freebee-game/enable#16]
Add word to puzzle:  neopreen

**Comment by ibara** [comment]
Do you mean neoprene, the synthetic rubber?

**Comment by margowolf52** [comment]
Right, did I misspell it?  I thought I tried both ways, but perhaps I hit a wrong key.  ThanksSent from my T-Mobile 5G Device
-------- Original message --------From: Brian Callahan ***@***.***> Date: 8/7/21  6:12 PM  (GMT-06:00) To: freebee-game/enable ***@***.***> Cc: margowolf52 ***@***.***>, Author ***@***.***> Subject: Re: [freebee-game/enable] Addto puzzle the word (#16) 
Do you mean neoprene, the synthetic rubber?

**Comment by ibara** [comment]
Hmm, the dictionary has neoprene and neoprenes but not neopreen. I haven't seen the neopreen spelling anywhere and Google and DDG think I meant "neoprene" if I try searching for "neopreen."

If you can (I know it's difficult a lot of the time), try again and see if neoprene works. If it doesn't that's a bug.

In any event, thanks for opening the issue.
