### ISSUE TITLE
Add alter

### ISSUE THREAD

**Issue by HollyJannette7** [freebee-game/enable#180]

**Comment by ibara** [comment]
This word is already in the dictionary. If there is a game where this is a valid word and it wasn't accepted, please take a screenshot and post it here.

**Comment by HollyJannette7** [comment]
![image](https://user-images.githubusercontent.com/52506786/167227886-2b54f2b1-8877-4ee1-9c6b-ef6e7e0f8ba2.png)

**Comment by HollyJannette7** [comment]
it didn't accept altar either

**Comment by ibara** [comment]
There is no r in this game: aethsul

**Comment by HollyJannette7** [comment]
oof I JUST noticed that. I was playing two games thanks!
