### ISSUE TITLE
Words not accepted, but then included in following day’s solution

### ISSUE THREAD

**Issue by Paulv66** [freebee-game/enable#198]
Just looking at yesterday’s results and it includes several words that were rejected when I tried to enter them, such as reemergence, etc.  Very frustrating.

**Comment by Paulv66** [comment]
For example, today I tried to enter the word unmute (as in, unmute a TV) and it is not being accepted as an answer.  I bet it will be one of the solutions shown tomorrow.

**Comment by ibara** [comment]
Unmute will not appear in tomorrow's solutions, as it was just added to the dictionary a few hours ago (after the game sheet was made).
https://github.com/freebee-game/enable/pull/200
