### ISSUE TITLE
Add giclee

### ISSUE THREAD

**Issue by Jifernan19** [freebee-game/enable#2]
its a printing process

**Comment by ibara** [comment]
Hello --

Thanks. All the dictionaries I've looked at spell the word giclée with that accented é. Not sure how to represent that in-game, since accented letters are never offered.

**Comment by Jifernan19** [comment]
Thanks Brian.  That makes sense then.  My bad.  Regards and thanks for
keeping up with the excellent game.

**Comment by ibara** [comment]
No worries. Don't apologize. I'd rather have suggestions that I have to think through than no suggestions at all. Keep them coming.
