### ISSUE TITLE
Add "wilco"

### ISSUE THREAD

**Issue by 1nan1ty** [freebee-game/enable#38]
Oxford American Dictionary:
wilco | ˈwilkō |
exclamation
expressing compliance or agreement, especially acceptance of instructions received by radio: roger, wilco.
ORIGIN
1940s (originally in military use): abbreviation of will comply.

**Comment by ibara** [comment]
According to the dictionary itself, wilco is already in there. (line 166833)

**Comment by 1nan1ty** [comment]
Okay, but it was rejected when I was playing. Tried it several times.

**Comment by ibara** [comment]
Next time this happens, please take a screenshot to show me. It's effectively impossible for me to debug a problem like this otherwise.

**Comment by 1nan1ty** [comment]
I would hardly have suggested the word had it been accepted. And no, I did
not misspell it.

**Comment by 1nan1ty** [comment]
Okay.

**Comment by ibara** [comment]
I'm not saying I don't believe you. I'm saying I don't have enough to debug. I'd have to recreate your exact game.

**Comment by 1nan1ty** [comment]
I know. Thanks.

**Comment by 1nan1ty** [comment]
I appreciate all your hard work on the game.

**Comment by 1nan1ty** [comment]
The New York Times puzzle has rejected such words as "undaunted" and
"unclouded," but those folks would never admit that the words were valid.
