### ISSUE TITLE
add to dictionary: wheelset; wheelsets

### ISSUE THREAD

**Issue by johndmcvay** [freebee-game/enable#39]
Thank you!!

**Comment by ibara** [comment]
✔️

**Comment by Aethelbeorn** [comment]
There is word asinus too, which stays for a braying animal (ass/donkey)
Though it is latin(?)

**Comment by ibara** [comment]
> There is word asinus too, which stays for a braying animal (ass/donkey) Though it is latin(?)


Please open a new issue for a new word. Otherwise it will get lost.

**Comment by retroodux** [comment]
Wheelset is a technical dictionary term and isk other usage?
