### ISSUE TITLE
Add to dictionary: voted

### ISSUE THREAD

**Issue by BrantleeSR** [freebee-game/enable#4]
voted - what, you've never voted???

**Comment by ibara** [comment]
Voted is in the dictionary, line 164452.
Was there a game you played where voted was a valid word and it was rejected?

**Comment by BrantleeSR** [comment]
Yep. Tried several times. It was within the past 2 weeks, but I can't say exactly which game.

**Comment by ibara** [comment]
If it happens again definitely let me know, since that is a bug.
