### ISSUE TITLE
Delete mumm, migg, immy, pigmy

### ISSUE THREAD

**Issue by Floccus** [freebee-game/enable#405]
None of these are English words.

**Comment by ibara** [comment]
https://scrabblewordfinder.org/dictionary/mumm
https://www.thefreedictionary.com/mumm

https://scrabblewordfinder.org/dictionary/migg

https://scrabblewordfinder.org/dictionary/immy
https://www.thefreedictionary.com/immy

https://scrabblewordfinder.org/dictionary/pigmy
