### ISSUE TITLE
Please add arrases, ecos, nenes, oscar, oscars, and soces

### ISSUE THREAD

**Issue by MickQueen** [freebee-game/enable#484]

**Comment by novalis** [comment]
"soces" is not in OED, and Google Books doesn't seem to return any reasonable English usage of it.

**Comment by MickQueen** [comment]
words made with Soces, words with soces, anagram of Soces

| 
| 
|  | 
words made with Soces, words with soces, anagram of Soces

words created with Soces, words starting with Soces, words start Soces
 |

 |

 |




    On Thursday, September 15, 2022 at 05:33:22 PM EDT, novalis ***@***.***> wrote:  
 
 


"soces" is not in OED, and Google Books doesn't seem to return any reasonable English usage of it.

**Comment by novalis** [comment]
I think the OSPD might have gone out on a limb here. 

If the idea is to copy the OSPD (or, perhaps, the NASPA Word List), well, they get kinda litigious...
