### ISSUE TITLE
Remove suffix formations -er, -ness, etc if forms not common usage

### ISSUE THREAD

**Issue by retroodux** [freebee-game/enable#50]
Aborter, accidentalness, bandager

Just for examples but hundreds of these suffixing noun forms onto every word, every possibility and some nonsense suffixing forms:

(Barbarousnesses. and other plural forms of adjectives, these are errors)

**Comment by ibara** [comment]
Please feel free to open requests as you find them.
However, I'll caution that at least part of what makes any word game interesting is the potential to learn new words.
Additionally, barbarousness is a noun: https://www.merriam-webster.com/thesaurus/barbarousness
It doesn't appear to have a plural, but it is a noun.
