### ISSUE TITLE
add bonobo back to list

### ISSUE THREAD

**Issue by gdginger** [freebee-game/enable#560]
CONGRATULATIONS! THIS IS AN OFFICIAL SCRABBLE WORD. 
BONOBO AN ANTHROPOID APE
RELATED WORDS: BONOBOS

I have successfully used this word 2-4 times in the past few months, so assume someone recently removed it?

**Comment by ibara** [comment]
I don't believe bonobo(s) was ever in this dictionary.

**Comment by gdginger** [comment]
Sorry, my mistake. They can be added tho?
________________________________
From: Brian Callahan ***@***.***>
Sent: Wednesday, August 17, 2022 10:42 AM
To: freebee-game/enable ***@***.***>
Cc: Gingerich, Gregory D ***@***.***>; Author ***@***.***>
Subject: [External] Re: [freebee-game/enable] add bonobo back to list (Issue #560)


I don't believe bonobo(s) was ever in this dictionary.
