### ISSUE TITLE
Stuck on yesterday’s letters

### ISSUE THREAD

**Issue by Paulv66** [freebee-game/enable#616]
A new game has not come up today. Every time I go into the app, it reloads yesterday’s letters.

**Comment by ibara** [comment]
Yes I know. I moved house yesterday and don't have Internet set up at my new home. I will fix it tonight.

**Comment by Paulv66** [comment]
Thanks Brian

I really appreciate all the work you’re doing in maintaining the website.

Best wishes
Paul

**Comment by ibara** [comment]
Fixed now. Sorry for the delay.

**Comment by Paulv66** [comment]
Awesome, thanks!
