### ISSUE TITLE
pls add 'bonobo'

### ISSUE THREAD

**Issue by mungbean** [freebee-game/enable#850]

**Comment by gdginger** [comment]
bonobo is a legitimate scrabble word:
BONOBO AN ANTHROPOID APE
RELATED WORDS: BONOBOS
https://scrabble.hasbro.com/en-us/tools#dictionary
a rare anthropoid ape (Pan paniscus) that has a more slender build and longer limbs than the related common chimpanzee 
(P. troglodytes) and that inhabits a small geographic region in equatorial Africa south of the Congo River
https://www.merriam-webster.com/dictionary/bonobo
but it will never be added to freebee dictionary. No one is sure why.
