### ISSUE TITLE
Incorrect Queen Bee score

### ISSUE THREAD

**Issue by steamboattrader** [freebee-game/enable#863]
OK, finally happened again.  This morning the Queen Bee score shows as 123, but I scored 133 🤷‍♂️.  Screen shots attached
<img width="1079" alt="queen bee november 20 my score" src="https://user-images.githubusercontent.com/107891776/203085322-a426d5b4-dd40-42c6-aede-ae3f0033db6f.png">
<img width="1043" alt="Queen Bee score reported November 20" src="https://user-images.githubusercontent.com/107891776/203085360-a493e9ca-1326-4548-8715-5f2d798cded9.png">

_Originally posted by @steamboattrader in https://github.com/freebee-game/enable/issues/806#issuecomment-1322183377_

**Comment by Paulv66** [comment]
I’m puzzled by the above comment. The queen bee score is the total you need to match or exceed in order to achieve queen bee status. If the player scores 133 and the target is 123, then queen bee status is achieved.

What am I missing?

**Comment by steamboattrader** [comment]
The Queen Bee score is the highest score, not a target.

**Comment by Paulv66** [comment]
I think you have your wires crossed.  Queen Bee is achieved by reaching 70% of the maximum points available, rounded down to the next integer.

**Comment by Paulv66** [comment]
If you click on API, you find the following explanation:

Calculating rank

To calculate the score needed for Queen Bee rank, multiply the total value by 0.7 and truncate the result.
