### ISSUE TITLE
Remove Peculia pls

### ISSUE THREAD

**Issue by MeadowBanksy** [freebee-game/enable#932]
Surely Peculia without the "r" should be removed; It was just the pangram for a random puzzle I did. Ostensibly, it is a plural of a super archaic latin word "peculium", the savings of a son or slave, but its completely out of use, it isn't in any dictionaries, (except for wikionary which specifically has archaic words). idk

**Comment by ibara** [comment]
It's in the Merriam-Webster dictionary: https://www.merriam-webster.com/dictionary/peculia
And in every Scrabble/Words with Friends dictionary: https://www.scrabblewordsolver.com/define-a-word/peculia/
