### ISSUE TITLE
Please add "fest" and "fests"

### ISSUE THREAD

**Issue by MickQueen** [freebee-game/enable#939]

**Comment by skg** [comment]
Seven requests for fest so far - https://www.dictionary.com/browse/fest

https://github.com/freebee-game/enable/issues/939
#939 opened 2 days ago by [MickQueen](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3AMickQueen)

https://github.com/freebee-game/enable/issues/760
#760 opened on Oct 21 by [gdginger](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3Agdginger)

https://github.com/freebee-game/enable/issues/570
#570 opened on Aug 18 by [gdginger](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3Agdginger)

https://github.com/freebee-game/enable/issues/548
#548 opened on Aug 16 by [gunsnglitter69](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3Agunsnglitter69)

https://github.com/freebee-game/enable/issues/274
#274 opened on Jun 10 by [Imthewaldo](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3AImthewaldo)

https://github.com/freebee-game/enable/issues/273
#273 opened on Jun 10 by [genejeanie](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3Agenejeanie)

https://github.com/freebee-game/enable/issues/270
#270 opened on Jun 10 by [Mizlib](https://github.com/freebee-game/enable/issues?q=is%3Aissue+is%3Aopen+author%3AMizlib)
